export const ADD_INCOME = 'ADD_INCOME';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ADD_SAVING = 'ADD_SAVING';

export const SET_INCOME = 'SET_INCOME';
export const SET_EXPENSES= 'SET_EXPENSES';
export const SET_SAVINGS = 'SET_SAVINGS';

export const UPDATE_EXPENSE_DATA = 'UPDATE_EXPENSE_DATA';
export const UPDATE_SAVING_DATA = 'UPDATE_SAVING_DATA';
export const UPDATE_INCOME_DATA = 'UPDATE_INCOME_DATA';